/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:3.0.2")
    api("org.springframework.boot:spring-boot-starter-data-jpa:3.0.2")
    api("com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17")
    api("org.springframework.boot:spring-boot-configuration-processor:3.0.2")
    api("org.projectlombok:lombok:1.18.24")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.0.2")
    runtimeOnly("mysql:mysql-connector-java:8.0.32")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.2")
}

group = "com.pj"
version = "0.0.1-SNAPSHOT"
description = "JpaTest"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
