server:
  port: 8081

### Spring Properties
spring:
  application:
    name: pres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  # PRES SQL Server datasource Properties
  #  datasource:
  #    url: jdbc:mysql://localhost:33061/jpa_test
  #    username: root
  #    password: Test@2020
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=jpa_test;encrypt=false
    username: sa
    password: Test@2020
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # JPA properties
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: update
        show_sql: false


  # Spring Session properties
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
    timeout: 1h
    store-type: jdbc
